CREATE TABLE IF NOT EXISTS teams (
    id SERIAL PRIMARY KEY,
    version VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    roster VARCHAR NOT NULL,
    coach_id INTEGER REFERENCES users ON DELETE SET NULL,
    treasury INTEGER NOT NULL,
    external_logo_url VARCHAR,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP WITH TIME ZONE,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teams_staff (
    id SERIAL PRIMARY KEY,
    staff VARCHAR NOT NULL,
    number INTEGER NOT NULL,
    team_id INTEGER NOT NULL REFERENCES teams ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS players (
    id SERIAL PRIMARY KEY,
    version VARCHAR NOT NULL,
    name VARCHAR NOT NULL,
    position VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    retired_at TIMESTAMP WITH TIME ZONE,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS teams_players (
    number INTEGER NOT NULL,
    team_id INTEGER REFERENCES teams ON DELETE SET NULL,
    player_id INTEGER NOT NULL REFERENCES players ON DELETE SET NULL,
    contract_start TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    contract_end TIMESTAMP WITH TIME ZONE
);