CREATE TABLE IF NOT EXISTS bb_players_hatred (
    player_id INTEGER NOT NULL REFERENCES bb_players ON DELETE CASCADE,
    game_id INTEGER NOT NULL REFERENCES bb_games ON DELETE RESTRICT,
    keyword VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    recovered_at TIMESTAMP WITH TIME ZONE
);