CREATE TABLE IF NOT EXISTS rpg_games (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    external_logo_url VARCHAR,
    description TEXT NOT NULL DEFAULT '',
    rules_system VARCHAR DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP WITH TIME ZONE,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rpg_characters (
    id SERIAL PRIMARY KEY,
    game_id INTEGER REFERENCES rpg_games ON DELETE RESTRICT,
    name VARCHAR NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    user_id INTEGER REFERENCES users ON DELETE SET NULL,
    external_image_url VARCHAR,
    notes TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP WITH TIME ZONE,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rpg_characters_profiles (
    id SERIAL PRIMARY KEY,
    character_id INTEGER REFERENCES rpg_characters ON DELETE CASCADE,
    profile JSONB DEFAULT NULL,
    current_profile BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP WITH TIME ZONE,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)