CREATE TABLE IF NOT EXISTS rpg_campaigns (
    id SERIAL PRIMARY KEY,
    game_id INTEGER REFERENCES rpg_games ON DELETE RESTRICT,
    name VARCHAR NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    game_master_id INTEGER REFERENCES users ON DELETE SET NULL,
    external_image_url VARCHAR,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP WITH TIME ZONE,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rpg_arcs (
    id SERIAL PRIMARY KEY,
    campaign_id INTEGER NOT NULL REFERENCES rpg_campaigns ON DELETE RESTRICT,
    position INTEGER NOT NULL DEFAULT 0,
    name VARCHAR NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    external_image_url VARCHAR,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP WITH TIME ZONE,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rpg_sessions (
    id SERIAL PRIMARY KEY,
    arc_id INTEGER NOT NULL REFERENCES rpg_arcs ON DELETE RESTRICT,
    position INTEGER NOT NULL DEFAULT 0,
    name VARCHAR NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    external_image_url VARCHAR,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    planned_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP WITH TIME ZONE,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rpg_sessions_characters (
    session_id INTEGER NOT NULL REFERENCES rpg_sessions ON DELETE RESTRICT,
    character_id INTEGER NOT NULL REFERENCES rpg_characters ON DELETE RESTRICT
)