CREATE TABLE IF NOT EXISTS bb_coaches_elo (
    coach_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE,
    game_id INTEGER NOT NULL REFERENCES bb_games ON DELETE RESTRICT,
    elo INTEGER NOT NULL
);