CREATE TABLE IF NOT EXISTS bb_players_resurrections (
    player_id INTEGER NOT NULL REFERENCES bb_players ON DELETE CASCADE,
    game_id INTEGER NOT NULL REFERENCES bb_games ON DELETE RESTRICT,
    dead_player_id INTEGER NULL REFERENCES bb_players ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);